services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: ./apps/web/Dockerfile
        restart: unless-stopped
        ports:
            - 3000:3000
        networks:
            - app_network
        environment:
            - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}

    api:
        container_name: api
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        restart: unless-stopped
        ports:
            - 3001:3001
        networks:
            - app_network
        depends_on:
            - mongodb
        environment:
            - CLIENT_URL=${CLIENT_URL}
            - API_MONGODB_URI=mongodb://mongodb:27017/find-my-mines
            - API_SECRET=${API_SECRET}
            - API_GOOGLE_CLIENT_URL=${API_GOOGLE_CLIENT_URL}
            - API_GOOGLE_CLIENT_ID=${API_GOOGLE_CLIENT_ID}
            - API_GOOGLE_CLIENT_SECRET=${API_GOOGLE_CLIENT_SECRET}

    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
        networks:
            - app_network

volumes:
    mongodb_data:

networks:
    app_network:
        driver: bridge
