import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

const monserrat = Montserrat({
    variable: '--font-montserrat',
    display: 'swap',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${monserrat.className} bg-gray text-white`}>
                {children}
            </body>
        </html>
    );
}
