import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import SocketContextProvider from './_contexts/socket';
import GameContextProvider from './_contexts/game';

const monserrat = Montserrat({
    variable: '--font-montserrat',
    display: 'swap',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Find My Mines',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${monserrat.className} bg-gray text-white`}>
                <SocketContextProvider>
                    <GameContextProvider>
                        <>{children}</>
                    </GameContextProvider>
                </SocketContextProvider>
            </body>
        </html>
    );
}
